### ISSUE TITLE
A ")" was exected

### ISSUE THREAD

**Issue by truegold** [ThomasMaul/ErrorHandler#1]
Hi Thomas,

ON ERR CALL(Formula(ErrorHandler).source; ‘k92;2‘)

Where is the missing ")" supposed to get set? I tried different places and the error persists.

Error when executing the method "On Startup" at line number 1

A ")" was expected.

Error code: 58 (4DRT)
A ")" was expected.
component: '4DRT'
task -6, name: 'P_1'

Call chain:
[
	{
		"type": "databaseMethod",
		"name": "On Startup",
		"line": 1,
		"database": "ErrorHandler"
	}
]

Thanks,
John...

**Comment by ThomasMaul** [comment]
The project was updated to support the latest features added with 4D v19 R8, so you need this version or 4D v20 to use it as described.

You can use the concept (without global error handler) as described in the original post, see history:
https://github.com/ThomasMaul/ErrorHandler/tree/a3228b1c248062247374b3b64583458f1a7a1b09
